// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/1/2025, 11:41:38 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["D:/My Working Project File/Python Project/full_stack_final_project/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/My Working Project File/Python Project/full_stack_final_project/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/My Working Project File/Python Project/full_stack_final_project/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/My Working Project File/Python Project/full_stack_final_project/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/My Working Project File/Python Project/full_stack_final_project/frontend/plugins/**/*.{js,ts,mjs}","D:/My Working Project File/Python Project/full_stack_final_project/frontend/composables/**/*.{js,ts,mjs}","D:/My Working Project File/Python Project/full_stack_final_project/frontend/utils/**/*.{js,ts,mjs}","D:/My Working Project File/Python Project/full_stack_final_project/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/My Working Project File/Python Project/full_stack_final_project/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/My Working Project File/Python Project/full_stack_final_project/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/My Working Project File/Python Project/full_stack_final_project/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;