"""Initial migration

Revision ID: 51705c6c1107
Revises: cd1b3c6a14ab
Create Date: 2025-07-31 08:49:15.768589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51705c6c1107'
down_revision: Union[str, Sequence[str], None] = 'cd1b3c6a14ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image', sa.String(), nullable=True))
    op.add_column('products', sa.Column('is_active', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('in_stock', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'in_stock')
    op.drop_column('products', 'is_active')
    op.drop_column('products', 'image')
    # ### end Alembic commands ###
